Add controllers
LapshYP/java-shareit pull request #1
Opened 2023-06-13 16:35 UTC by LapshYP

Добрый вечер!
Тз 13 на проверку

2023-06-14 20:47 UTC, z8q requested changes

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@RequiredArgsConstructor
RequiredArgsConstructor не совсем понятно для чего.
`new User("name");`  или `new User("name", "email@yandex.ru");` – в таком виде не даст создать пользователя

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private UserMapper userMapper
final

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +@Mapper(componentModel = "spring")
В целом, допустимо)

Но если названия полей будут отличаться или будет дополнительная логика, то надо будет еще посмотреть, mapstruct позволяет такие случаи тоже обрабатывать.

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return savedUserDTO;
Преобразования из/в dto рекомендую делать в сервисных классах,  чтобы в самом контроллере получилось что-то такое:
`@PostMapping`
`public UserDTO createUser(@Valid @RequestBody UserDTO userDTO) {`
`        return userService.createUserSerivce(userDTO);`
`}`

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDTO> createItem(@Valid @RequestBody ItemDTO itemDTO, @RequestHeader("X-Sharer-User-Id") int userDTOId) {
тоже можно просто @RequestHeader("X-Sharer-User-Id") int `userId`

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @GetMapping("/{itemDtoId}")
тут и в 40-й строке можно просто itemId

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserRepositoryImpl userRepository;
Тоже можно было бы указать интерфейс

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        String textToLowerCase = text.toLowerCase();
Если текст придет null, тут упадем с NullPointerException

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        boolean isRightUser = itemRepository.getItemStorage().get(itemId).getOwnerId() == userId ? true : false;
Если придет несуществующий id вещи, то тут упадем с NullPointerException

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            log.error("Вещь с именем = {} и описанием {} не может быть обновлена этим пользователем {}", item.getName(), userId);
В сообщении три {} {} {}, а мы передаем только два параметра

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!userRepository.getUserStorage().keySet().contains(userId)) {
Можно заменить на userRepository.getUserStorage().containsKey(userId)

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        return userStorage.values().stream()
Можно заменить return new ArrayList<>(userStorage.values());

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDTO> getItemById(@Valid @PathVariable int itemDtoId, @RequestHeader("X-Sharer-User-Id") int userId) {
Если делаем get пользователя или вещи по несуществующему id, то получаем код ответа 200 без какого либо сообщения

2023-06-14 20:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDTO updateUser(@RequestBody UserDTO userDTO, @PathVariable int userId) {
При обновлении нет валидации, допускается сохранить что-то такое:
`{`
`	"name": "Bob",`
`	"email": "@bob@yandex.ru"`
`}`

2023-06-15 17:50 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@RequiredArgsConstructor
убрал @RequiredArgsConstructor

2023-06-15 17:55 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    private UserMapper userMapper
добавил модификатор final

2023-06-15 18:05 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDTO> createItem(@Valid @RequestBody ItemDTO itemDTO, @RequestHeader("X-Sharer-User-Id") int userDTOId) {
поправил на userId

2023-06-15 18:06 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @GetMapping("/{itemDtoId}")
поправил

2023-06-15 18:08 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserRepositoryImpl userRepository;
поменял

2023-06-15 18:13 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@RequiredArgsConstructor
RequiredArgsConstructor выполнял функцию NoArgsConstructor
без него не запускалась программа.

добавил - NoArgsConstructor

2023-06-15 18:19 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        String textToLowerCase = text.toLowerCase();
добавил проверку на null

2023-06-15 19:06 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        boolean isRightUser = itemRepository.getItemStorage().get(itemId).getOwnerId() == userId ? true : false;
добавил проверку на то, что вещь - существует

2023-06-15 19:07 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            log.error("Вещь с именем = {} и описанием {} не может быть обновлена этим пользователем {}", item.getName(), userId);
поправил

2023-06-15 19:09 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!userRepository.getUserStorage().keySet().contains(userId)) {
заменил

2023-06-15 19:11 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        return userStorage.values().stream()
заменил

2023-06-17 17:00 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDTO updateUser(@RequestBody UserDTO userDTO, @PathVariable int userId) {
добавил валидацию почты

2023-06-18 09:16 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return savedUserDTO;
перенес в сервисные классы

2023-06-19 18:47 UTC, z8q approved these changes

2023-06-19 18:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserDTO.java
> +    @Email(message = "Email is not valid", regexp = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")
Даже без regexp будет происходить валидация, 
но возможно ты хотел ограничить ввод определенными символами,
Если так, то норм)

2023-06-19 18:47 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDTO updateUser(@RequestBody UserDTO userDTO, @PathVariable int userId) {
Тут на самом деле не хватает `@Valid`, потому что сейчас допускается обновить пользователя с пустыми полями:
{
	"name": "",
	"email": ""
}

У вещей так же

2023-07-01 12:02 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDTO> getItemById(@Valid @PathVariable int itemDtoId, @RequestHeader("X-Sharer-User-Id") int userId) {
исправил

2023-07-01 12:03 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDTO updateUser(@RequestBody UserDTO userDTO, @PathVariable int userId) {
добавил валидацию @Valid

2023-07-01 14:45 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      public UserDTO updateUser(@RequestBody UserDTO userDTO, @PathVariable int userId) {
и убрал т.к. она вешает тесты

2023-07-01 14:49 UTC, merged