Add bookings
LapshYP/java-shareit pull request #5
Opened 2023-07-01 17:42 UTC by LapshYP

добрый вечер!
тз 14 на проверку

2023-07-03 19:36 UTC, z8q requested changes

2023-07-03 19:36 UTC, z8q commented on pom.xml
>  	<dependencies>
По сборке посмотрел,
ругается все таки на постман, с 924 строки начинают появляться ошибки.

2023-07-03 19:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NotNull
стоит ли тут применять валидацию?
Лучше будет оставить это для логики работы с dto

В других моделях можно тоже посмотреть

2023-07-03 19:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals(State.ALL.toString())) {
можно switch-case попробовать применить с енамами
https://stackoverflow.com/questions/2836286/enums-use-in-switch-case

2023-07-03 19:36 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>      public UserDTO deleteUserService(int userId) {
В этом сервисе, в методах, где идет несколько обращений к базе, можно было бы обернуть в транзакции

2023-07-04 18:11 UTC, LapshYP commented on pom.xml
>  	<dependencies>
обновил пом - файл и все заработало

2023-07-04 18:12 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @NotNull
перенес валидацию в сервисный класс, 
валидацию хочу проводить через pojo

2023-07-04 18:13 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (state.equals(State.ALL.toString())) {
поменял на switch-case

2023-07-05 06:29 UTC, z8q approved these changes

2023-07-05 17:30 UTC, merged