Add item requests
LapshYP/java-shareit pull request #7
Opened 2023-07-16 10:03 UTC by LapshYP

Добрый день!
Тз 15 на проверку

2023-07-16 12:37 UTC, LapshYP commented
в

2023-07-19 16:20 UTC, z8q requested changes

2023-07-19 16:20 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>  import java.util.Set;
Похоже в контроллере item не хватает вот этого пункта из тз:
```
Добавлена пагинация в эндпоинты GET /items, GET /items/search
```

2023-07-19 16:20 UTC, z8q commented on src/test/java/ru/practicum/shareit/user/dto/UserDTOTest.java
> +//@JsonTest
Почему решил закомментировать? Может тогда убрать

2023-07-20 03:06 UTC, LapshYP commented on src/test/java/ru/practicum/shareit/user/dto/UserDTOTest.java
> +//@JsonTest
я хотел реализовать проверку ДТО классов именно этим способом, проверка сереализации и десереализации но по какой-то не понятной причине этот тест вешается из за аннотации - @JsonTest

наставник - Артур вроде должен был посмотреть, но так ничего внятного не сказал, почему не работает этот тест (начинаются инициализироваться какие-то внутренние бины и все падает)

может посмотришь в чем причина?

2023-07-20 03:10 UTC, LapshYP commented on src/test/java/ru/practicum/shareit/user/dto/UserDTOTest.java
> +//@JsonTest
также никто не ответил как протестировать - JdbcSQLIntegrityConstraintViolationException
выкидывающее исключение в случае добавления в базу не уникального экземпляра.

это не кастомное исключение и работает само по себе.

2023-07-20 04:03 UTC, LapshYP commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>  import java.util.Set;
пагинацию добавил

2023-07-20 23:01 UTC, z8q approved these changes

2023-07-21 03:10 UTC, merged