Add docker
LapshYP/java-shareit pull request #8
Opened 2023-07-23 13:26 UTC by LapshYP

Добрый день!
тз16 на проверку

2023-07-24 20:28 UTC, z8q requested changes

2023-07-24 20:28 UTC, z8q commented on server/src/main/java/ru/practicum/shareit/user/model/User.java
> +//    @Email(message = "Email is not valid", regexp = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")
закомментированные строки стоит убрать

2023-07-24 20:28 UTC, z8q commented on server/pom.xml
> +            <groupId>jakarta.validation</groupId>
Все связнанное с валидацией, в том числе зависимости, стоит убрать и server. Оставить только в gateway

2023-07-24 20:28 UTC, z8q commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public ItemDTO updateService(ItemDTO itemDTO, int itemId, int userId) {
В updateService дважды делаем itemRepoJpa.findById(itemId) в строках 69 и 73
Хотя на 69 уже можно было бы получить возвращаемый объект и использовать его

2023-07-24 20:28 UTC, z8q commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +//
Стоит почистить код от закомментированных блоков

2023-07-25 03:32 UTC, LapshYP commented on server/src/main/java/ru/practicum/shareit/user/model/User.java
> +//    @Email(message = "Email is not valid", regexp = "^[a-zA-Z0-9_!#$%&'*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$")
убрал закомментированые строки

2023-07-25 03:32 UTC, LapshYP commented on server/pom.xml
> +            <groupId>jakarta.validation</groupId>
почистил зависимости и все оставшееся связанное с валидацией

2023-07-25 03:34 UTC, LapshYP commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      public ItemDTO updateService(ItemDTO itemDTO, int itemId, int userId) {
ага, убрал вторую строчку, и перенес объявление в первую

2023-07-25 03:35 UTC, LapshYP commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +//
почистил код от закомментированного

спасибо

2023-07-25 18:04 UTC, z8q approved these changes

2023-08-28 07:48 UTC, merged